apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo-app-cert
  namespace: k8s-local
spec:
  secretName: echo-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - __INGRESS_HOST__
